### ISSUE TITLE
Distorted audio and no progress when navigating through song with arrow keys

### ISSUE THREAD

**Issue by BlobCodes** [vixalien/decibels#46]
## Problem

Since the `GtkScale` under the waveform can be focused, it is (kinda) possible to navigate through the song using the keyboard by `Tab`-ing to the scale and then using the arrow keys.

However, since the `page-increment` and `step-increment` values of the `GtkAdjustment` given to the scale are both zero, the position remains unchanged when trying this.

While this is happening, the audio also quickly repeats, leading to a distorted sound.

## Suggested solution

I think the best solution would be to make the `GtkScale` unfocussable, maybe adding more sophisticated logic to the program for navigating through the audio file via the keyboard.

## Alternative solution

The `page-increment` and `step-increment` values of the `GtkAdjustment` could be updated to practical values, which would also fix #7. This is still bothersome to use on a keyboard, and some additional logic must be added to ensure the `GtkScale` never goes below 0/above the maximum.

## Appendix

Here's a video where the specified current behaviour can be seen and heard:
[Screencast_16.12.2023_04:28:36.webm](https://github.com/vixalien/decibels/assets/14961554/732891e4-ba08-450d-a0c5-71c6e1fc664c)

**Comment by vixalien** [comment]
The issue should be fixed. The fix allows using the arrow keys to seek.

For the proposed solution allowing navigating through the audio file via the keyboard, Gtk won't allow this as it uses arrow keys for moving focus between elements. Overriding this behavior would require hacks if possible and may lead to bad UX problems.

**Comment by vixalien** [comment]
Could you test the latest CI build to see if the potential issue is present?

**Comment by vixalien** [comment]
Hi. your attached video seems to be broken.

And for the scrolling behavior, make sure to download the latest CI build. After you do so, please report the version installed.

**Comment by vixalien** [comment]
Okay, the video is now loaded. I'm unsure what behavior you are trying to show though

**Comment by vixalien** [comment]
> So now, laptop users with a touchpad can scroll from left to right, but you cannot scroll using a normal PC mouse because it can scroll only from top to bottom.

This is indeed true. I use a laptop, and scrolling left-to-right is most sensible. How I see it works is I can either choose to get horizontal or vertical scroll events, or both. In the "both directions" situation however, GTK doesn't report the direction currently being scrolled to so it's a bummer, and we have to choose one. 

Maybe switching to vertical is better.

> In the first ten seconds, I press the left arrow key repeatedly. There you can see the GtkScroll resetting to its previous position all the time.

This seems to be a GTK bug. GTK handles the scale scrolling, and when you under-scroll (scroll before 0), GTK should automatically clamp the value to 0. (by using the `lower` attribute.) I will be seeing if I can create a GTK issue.

> From 0:10 - 0:12, you can see that the user can scroll over the end, starting at the beginning.
When this happens, the song is paused. In the paused state, you cannot scroll over the end again.

This is because, when you scroll to the end, the audio is automatically restarted (in other words: seek to 0, and paused) so that's why the behavior ensues. What would you like to happen when you scroll over the end?

> In the last few seconds, you can see me pressing the right arrow key repeatedly. There, I'm never able to reach the end of the song. This is similar to the first bug.

Why would you want to skip to the very end of a track?
