### ISSUE TITLE
when decibels installed as flatpak, GNOME Places extension tries to open folders with decibels instead of nautilus

### ISSUE THREAD

**Issue by sebo505** [vixalien/decibels#58]
After I have installed decibels as flatpak via flathub, I can no more access folders like Music, Videos, Home etc via GNOME Places extension, since it now tries to open the folders with decibels instead of nautilus.

**Comment by vixalien** [comment]
You are probably using Arch Linux. Please see https://wiki.archlinux.org/title/File_manager_functionality#Directories_are_not_opened_in_the_file_manager

**Comment by sebo505** [comment]
Hi, I am actually on Solus with GNOME 45.3.
Following the Arch wiki, I was able to resolve the issue with
`xdg-mime default org.gnome.Nautilus.desktop inode/directory`
Though I would still consider it a bug that decibels obviously sets itself as default "file browser" on install.
I have also observed that this does not happen on Fedora.
You have any insights why this happens on Solus, but not on Fedora and are you planing to take action to prevent decibels settings itself as default file browser?
Thank you.

**Comment by vixalien** [comment]
This happens for apps like Amberol, G4Music and even VS Code, basically any app that can open directories (or in this case, files).

I believe this is caused by the Nautilus package not being set as a program that can open directories. Now, Fedora and Ubuntu will usually patch these "bugs" out, while DIY or upstream-preferring distros will leave the things as-is. This is probably a Nautilus issue, but good luck convincing the developers.

**Comment by sebo505** [comment]
Hey, thank you for your response, this has been  helpful to me.
I also found a pretty good [explanation](https://discourse.gnome.org/t/why-doesnt-default-applications-have-file-manager/14167/8) for this matter by the GNOME devs on GNOME discourse.
